# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- greenkeeper/*

variables:
  BuildConfiguration: 'Release'

jobs:

  - job: 'net_core'
    displayName: '.NET Core Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UseDotNet@2
        displayName: 'Install .net core 3.1'
        inputs:
          packageType: 'sdk'
          version: '3.1.100'

      - task: DotNetCoreCLI@2
        displayName: '.NET Core - Restore'
        inputs:
          command: 'restore'
          projects: './src'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        displayName: '.NET Core - Build'
        inputs:
          command: 'build'
          arguments: '-c $(BuildConfiguration) --no-restore'
          projects: './src'

      - task: DotNetCoreCLI@2
        displayName: '.NET Core - Run Tests'
        inputs:
          command: 'test'
          projects: './src'

  # Angular APP's
  - job: 'angular'
    displayName: 'Angular Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      # Admin UI
      - task: Npm@1
        displayName: 'NPM - Install - AdminUI'
        inputs:
          command: install
          workingDir: src/Frontend/Jp.AdminUI

      - task: Npm@1
        displayName: 'NPM - Build Prod - AdminUI'
        inputs:
          command: custom
          customCommand: 'run build'
          workingDir: src/Frontend/Jp.AdminUI

  - job: 'docker'
    displayName: 'Docker files'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: 'Docker - Build - AdminUI'
        inputs:
          command: 'build'
          Dockerfile: '**/admin-ui.dockerfile'

      - task: Docker@2
        displayName: 'Docker - Build - API'
        inputs:
          command: 'build'
          Dockerfile: '**/api-light.dockerfile'
